title = "Ninjabot"
baseURL = "https://rodrigo-brito.github.io/ninjabot/"
theme = "docsy"

# Language settings
languageCode = "en-us"
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

# [services]
# [services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
# id = "UA-00000000-0"

[menu]
  [[menu.main]]
    identifier = "docs"
    name = "Documentation"
    pre = "<i class='fa fa-book'></i>"
    url = "docs/"
    weight = 1

  [[menu.main]]
    identifier = "github"
    name = "Github"
    pre = "<i class='fab fa-github'></i>"
    url = "https://github.com/rodrigo-brito/ninjabot"
    weight = 2

